name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Run build
      run: |
      export PATH="/home/runner/.config/.foundry/bin:$PATH"
      make build

    - name: Run tests
      run: |
      export PATH="/home/runner/.config/.foundry/bin:$PATH"
      make test
