name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        source /home/runner/.bashrc
        foundryup

    - name: Run build
      run: make build

    - name: Run tests
      run: make test
