name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Run build
      run: |
      source $GITHUB_PATH
      make build

    - name: Run tests
      run: |
      source $GITHUB_PATH
      make test
